### ISSUE TITLE
Update User Settings menu item

### ISSUE THREAD

**Issue by aatteia** [AtlasOfLivingAustralia/front-end-static#12]
Change User Settings dropdown menu to be a login link (and remove register link).

Note: If the user wants to register, they can use the link in the login auth screen.  But I still want the user setting menu to work as it does now when you are logged in.

**Comment by sadeghim** [comment]
My suggestion is that, if the user is not logged in, can only see Login or Register instead of "User settings". This is a direct guide for a user to start working with ALA. 

@aatteia  What do you think?

**Comment by aatteia** [comment]
I'm think we are talking about the same thing.  If so, then I love your idea.  I think it is the best idea that I've ever had. :)

When not logged in, they will see the 'log in' link only (so no dropdown) and when logged in, they will see the 'user settings' menu as they do now.

**Comment by aatteia** [comment]
When not logged in, the user now sees "Sign in".

The next step is to connect the sign in link to the https://auth.ala.org.au/cas/login screen.
