### ISSUE TITLE
Update primary and footer menu for user testing

### ISSUE THREAD

**Issue by aatteia** [AtlasOfLivingAustralia/front-end-static#25]
The main menu and the footer menu have been updated.  The working example is here:
https://rawgit.com/AtlasOfLivingAustralia/front-end-static/master/ALA%20Website%20Recreation%20in%20Bootstrap%203/index-alt-version-2.html

The menu structure has been changed to this:
https://github.com/AtlasOfLivingAustralia/front-end-static/wiki/Menu-structure-2016

Note that only the menu item groupings have changed, so there is no new content in terms of the IA.

I need this to be deployed to wptest2016 for our first round of user testing tomorrow morning.

Thanks in advance, and let me know if you have any questions.
Adam.

**Comment by Tasilee** [comment]
Main Menu: 

1. I'd like to see more indicative images associated with the main portals.
2. The difference between "Collections" and "Data sets" is too subtle for the home page. I'd suggest  "Data collections" with links to more obvious categories as "Specimen collections" and "Submitted datasets"

Menu Structure:

1. "Mapping analysis - Spatial Portal" should now be "Spatial (research) Portal"
2. As above on "Collections" vs "Data sets"
3. Good to see an "Education resources" landing page but suggest "Educational resources"
4. "Australian iconic species" is too specific and isn't complementary with "Explore your area". Suggest "Explore species" with some lists such as "Iconic", "Endangered", "Invasive" and "Lifeforms" on the landing page.
5. Add "Species lists" to Search/analyse
6. Add "PhyloLink" to Search/Analyse
7. "Upload a dataset for local analysis" to Search/Analyse

Record a sighting should only be in Contribute

Contribute/Participate should have links to ALA software

"Digitize a record" should be more generic as "Help liberate data" or similar.
