### ISSUE TITLE
Print rules in ala-styles.css

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/front-end-static#3]
Would be good to have a `@media print {...` rule that removes the display of elements that are web-ui only and makes printed version of the page look nice. In particular the footer is a problem with huge text and logos.

**Comment by aatteia** [comment]
Print styles completed and integrated into ala-styles.css file. CSS file can be found in Github front-end-static repo.

**Comment by djtfmartin** [comment]
Nice work :)
