### ISSUE TITLE
Update main menu items in wptest.ala.org.au

### ISSUE THREAD

**Issue by aatteia** [AtlasOfLivingAustralia/front-end-static#9]
Update main menu items, Explore, Contribute and Learn to match the following file:

https://rawgit.com/AtlasOfLivingAustralia/front-end-static/master/ALA%20Website%20Recreation%20in%20Bootstrap%203/index-alt-version.html 

**Note:** I've tweaked the menu item arrangement in the Explore menu.

Menu item changes are documented in Google Sheets document:

https://docs.google.com/a/iamadamatteia.com/spreadsheets/d/1c-Jd1DApg4QPZzMs5khOkVJ6PyPPtfDrAcsh9iYIcx0/edit?usp=sharing

**Comment by sadeghim** [comment]
The links in the file are not relative paths which cause issues whenever we deploy the file. I changed them to be relative paths (see: https://github.com/AtlasOfLivingAustralia/ala-wordpress-theme/blob/c785a4c392e9d0211c391f9188c2aa9c99b40089/template-part-topnav.php#L81).

Please change your files accordingly.

**Comment by aatteia** [comment]
Got it.  So instead of being relative URLs (for example, #communicate), they are absolute URLs (eg, http:// etc/etc/communicate).  And, just to confirm that I have this right, you are suggesting that I update my local files to match?

**Comment by aatteia** [comment]
Issue closed.
